### PR TITLE
change from switch to when-otherwise for integration

### PR DESCRIPTION
**Pull request by jerryduan07**

### CODE REVIEW

**Comment by edwardcwang** [comment]
Did we just not figure out why switch() was misbehaving?

Also please follow Chisel style (`when (...) {` and `} .elsewhen (...) {` for instance)

**Comment by jerryduan07** [comment]
> Did we just not figure out why switch() was misbehaving?
> 
> Also please follow Chisel style (`when (...) {` and `} .elsewhen (...) {` for instance)

No, there is a no such method error when elaborating

**Comment by edwardcwang** [comment]
I think that error shouldn't happen though. We may want to dig deeper to find out why it's happening.

**Comment by jerryduan07** [comment]
> I think that error shouldn't happen though. We may want to dig deeper to find out why it's happening.

I can keep this in another branch for now and move forward with integration. @Fibonacci12358 and I looked into it last week but couldn't find any precedents

**Comment by edwardcwang** [comment]
Alright that's fine, let's just merge this since it's not the end of the world.

**Pull request merged**
